In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
def type_to_df(df):
    df = df[['location','session_key','year','air_temperature','humidity','pressure','rainfall','track_temperature','wind_speed']]
    df_list = df.session_key.to_list()
    driver_df = lando_avg[lando_avg.session_key.isin(df_list)]
    driver_df = driver_df.merge(df, on = 'session_key', how = 'inner')
    return driver_df

In [3]:
lando_laps = pd.read_csv('../data/lando_laps.csv') # reads in Lando's lap stats

In [4]:
lando_laps = lando_laps[['session_key','driver_number','i1_speed','i2_speed','st_speed','lap_duration','duration_sector_1','duration_sector_2','duration_sector_3']]
# reduces df to only necessary columns

In [5]:
lando_avg = lando_laps.groupby(['session_key','driver_number']).agg({'i1_speed':'mean','i2_speed':'mean','st_speed':'mean','lap_duration':'mean','duration_sector_1':'mean','duration_sector_2':'mean','duration_sector_3':'mean'})
# avgerages out all the lap data by each race

In [6]:
lando_avg = lando_avg.reset_index()
lando_avg

,session_key,driver_number,i1_speed,i2_speed,st_speed,lap_duration,duration_sector_1,duration_sector_2,duration_sector_3
0,7779,4,281.542857,299.520000,303.800000,99.081959,36.846265,31.017400,31.226800
1,7787,4,251.053571,277.172414,278.836364,158.693088,31.539474,21.750000,104.543983
2,7953,4,227.159091,246.018182,287.137255,102.555704,34.876111,43.113073,24.596891
3,9070,4,188.104167,200.235294,314.901961,110.547980,39.435260,44.769392,26.321412
4,9078,4,210.306122,184.912281,305.543860,93.539375,31.907214,35.505877,26.184125
5,9094,4,178.128571,175.545455,275.584416,84.789566,22.157461,40.151571,22.468961
6,9102,4,261.500000,265.384615,303.693878,81.514094,25.029234,32.225277,24.348431
7,9110,4,244.984615,274.000000,309.157143,81.356696,22.581551,26.084600,32.683429
8,9118,4,300.466667,224.746479,297.126761,72.480386,18.510629,31.967338,22.146338
9,9126,4,276.950000,249.115385,283.615385,98.513431,32.141706,39.422135,26.900904
10,9133,4,280.629630,241.100000,289.540000,84.528464,30.854406,29.947000,23.746543
11,9141,4,307.289474,186.954545,302.485714,114.077605,33.502279,49.769409,30.840477
12,9149,4,269.078125,259.527778,279.109375,120.639662,64.688944,30.031875,25.963431
13,9157,4,311.888889,317.509804,319.363636,87.501580,28.742760,30.133510,28.649725
14,9165,4,279.771930,261.790323,282.036364,103.144508,30.204869,44.054726,28.882468
15,9173,4,266.265306,287.283019,284.377358,102.970846,37.844250,45.204321,20.324660
16,9181,4,272.895522,277.535211,327.470588,104.123943,48.384614,33.179296,22.608183
17,9189,4,167.666667,190.000000,237.500000,119.327000,32.584000,37.438000,48.730000
18,9197,4,288.500000,300.241379,305.206897,90.396474,18.683632,38.425345,33.306621
19,9205,4,298.950820,247.169014,287.863636,98.504143,41.165714,39.403845,18.502803
20,9213,4,211.600000,182.857143,295.250000,102.370545,28.062491,40.855750,33.441929
21,9221,4,225.274510,270.877193,293.511628,91.907857,34.509179,30.455421,27.331140
22,9472,4,233.605263,256.491228,296.325581,97.339857,31.555000,41.861333,23.954544
23,9480,4,277.162162,290.120000,293.660000,97.735816,35.675918,30.803340,31.221040
24,9488,4,272.653061,298.275862,289.250000,83.209877,28.914263,18.281690,36.017983
25,9496,4,278.157895,296.584906,293.320755,129.971442,67.424385,43.851736,19.364226
26,9507,4,205.755556,181.631579,306.298246,95.552804,32.446018,36.359158,26.730667
27,9515,4,216.865385,255.682540,291.190476,81.326016,25.822565,28.297127,27.202016
28,9523,4,192.633803,185.679487,278.910256,79.690416,20.650818,37.124205,22.051519
29,9531,4,212.203390,265.228571,283.671429,90.508464,25.849652,28.711857,36.030443
30,9539,4,261.396825,270.651515,310.065574,80.284508,24.023708,32.144727,24.114409
31,9550,4,300.442308,228.437500,297.062500,71.709254,18.091159,31.709219,21.893969
32,9558,4,295.934783,255.538462,301.634615,95.240373,31.022784,38.232865,25.980173
33,9566,4,277.611111,241.157143,287.541667,83.981754,30.611203,29.696471,23.688571
34,9574,4,327.473684,203.209302,315.225806,109.151667,31.559256,48.406884,29.240860
35,9582,4,286.823529,265.283582,296.721311,75.642409,25.744818,27.356209,22.545955
36,9590,4,315.111111,320.377358,325.588235,84.575173,28.171212,28.629057,27.836623
37,9598,4,190.914894,206.196078,314.627451,109.807780,39.580660,44.239941,26.078353
38,9606,4,283.810345,262.225806,280.479167,97.576180,29.098082,41.013226,27.477016
39,9617,4,211.936170,178.928571,299.178571,102.219836,27.522364,40.556982,34.126304
40,9625,4,281.469697,276.338028,320.403509,85.017157,30.588243,32.754620,21.991324
41,9636,4,280.553571,207.304348,243.208955,111.088221,43.711118,46.880797,20.448275
42,9644,4,178.756098,207.460000,314.880000,99.235959,29.067122,33.182880,37.010720
43,9655,4,228.097561,267.456522,266.645161,98.865667,36.905489,31.790543,30.538174
44,9662,4,286.116279,296.375000,303.392857,89.516714,18.380821,38.469860,32.665070
45,9673,4,259.808511,253.767857,291.727273,108.396418,28.763054,32.629250,47.009357

--- Rain Races ---

In [8]:
rain_race = pd.read_csv('../data/rain_race.csv') # reads in csv of all the rain races
lando_rain = type_to_df(rain_race)
lando_rain

,session_key,driver_number,i1_speed,i2_speed,st_speed,lap_duration,duration_sector_1,duration_sector_2,duration_sector_3,location,year,air_temperature,humidity,pressure,rainfall,track_temperature,wind_speed
0,9094,4,178.128571,175.545455,275.584416,84.789566,22.157461,40.151571,22.468961,Monaco,2023,77.118636,45.863636,1013.359659,1,102.660227,2.249710
1,9118,4,300.466667,224.746479,297.126761,72.480386,18.510629,31.967338,22.146338,Spielberg,2023,72.316471,52.045752,934.015686,1,89.697647,2.454852
2,9141,4,307.289474,186.954545,302.485714,114.077605,33.502279,49.769409,30.840477,Spa-Francorchamps,2023,64.172000,61.926667,966.627333,1,82.833200,3.567269
3,9149,4,269.078125,259.527778,279.109375,120.639662,64.688944,30.031875,25.963431,Zandvoort,2023,62.225359,70.775120,1007.824402,1,76.894067,6.311765
4,9205,4,298.950820,247.169014,287.863636,98.504143,41.165714,39.403845,18.502803,São Paulo,2023,68.828197,58.174863,927.900546,1,116.196721,2.928881
5,9531,4,212.203390,265.228571,283.671429,90.508464,25.849652,28.711857,36.030443,Montréal,2024,62.810545,75.703030,996.332727,1,73.665091,2.687112
6,9539,4,261.396825,270.651515,310.065574,80.284508,24.023708,32.144727,24.114409,Barcelona,2024,75.423567,63.433121,1001.353503,1,105.931847,4.740445
7,9550,4,300.442308,228.437500,297.062500,71.709254,18.091159,31.709219,21.893969,Spielberg,2024,84.966573,35.006993,932.862937,1,115.557762,3.730941
8,9558,4,295.934783,255.538462,301.634615,95.240373,31.022784,38.232865,25.980173,Silverstone,2024,60.387347,67.333333,992.126531,1,81.806122,3.016146
9,9636,4,280.553571,207.304348,243.208955,111.088221,43.711118,46.880797,20.448275,São Paulo,2024,70.992836,85.258706,926.456716,1,78.385373,1.646031

--- Hot Races ---

In [10]:
hot_race = pd.read_csv('../data/hot_race.csv') # reads in csv of all the hot races
lando_hot = type_to_df(hot_race)
lando_hot

,session_key,driver_number,i1_speed,i2_speed,st_speed,lap_duration,duration_sector_1,duration_sector_2,duration_sector_3,location,year,air_temperature,humidity,pressure,rainfall,track_temperature,wind_speed
0,9133,4,280.629630,241.100000,289.540000,84.528464,30.854406,29.947000,23.746543,Budapest,2023,83.855366,32.804878,988.401829,0,119.442683,3.223190
1,9157,4,311.888889,317.509804,319.363636,87.501580,28.742760,30.133510,28.649725,Monza,2023,84.794231,42.320513,1000.561538,0,109.270769,2.549606
2,9165,4,279.771930,261.790323,282.036364,103.144508,30.204869,44.054726,28.882468,Marina Bay,2023,85.719773,72.028409,1008.978409,0,97.559886,3.167389
3,9213,4,211.600000,182.857143,295.250000,102.370545,28.062491,40.855750,33.441929,Austin,2023,85.928214,41.910714,993.730952,0,105.131429,7.414057
4,9221,4,225.274510,270.877193,293.511628,91.907857,34.509179,30.455421,27.331140,Lusail,2023,88.628228,73.177215,1009.776582,0,98.465570,1.986399
5,9507,4,205.755556,181.631579,306.298246,95.552804,32.446018,36.359158,26.730667,Miami,2024,83.339452,59.047945,1016.451370,0,112.272603,6.867284
6,9550,4,300.442308,228.437500,297.062500,71.709254,18.091159,31.709219,21.893969,Spielberg,2024,84.966573,35.006993,932.862937,1,115.557762,3.730941
7,9566,4,277.611111,241.157143,287.541667,83.981754,30.611203,29.696471,23.688571,Budapest,2024,83.882968,46.922581,981.676774,0,112.849032,2.795528
8,9590,4,315.111111,320.377358,325.588235,84.575173,28.171212,28.629057,27.836623,Monza,2024,91.582707,32.285714,993.228571,0,120.760301,3.397549
9,9606,4,283.810345,262.225806,280.479167,97.576180,29.098082,41.013226,27.477016,Marina Bay,2024,87.415250,74.650000,1008.024375,0,97.602125,2.136335

--- Cold Races ---

In [12]:
cold_race = pd.read_csv('../data/cold_race.csv') # reads in csv of all the cold races
lando_cold = type_to_df(cold_race)
lando_cold

,session_key,driver_number,i1_speed,i2_speed,st_speed,lap_duration,duration_sector_1,duration_sector_2,duration_sector_3,location,year,air_temperature,humidity,pressure,rainfall,track_temperature,wind_speed
0,7787,4,251.053571,277.172414,278.836364,158.693088,31.539474,21.750000,104.543983,Melbourne,2023,63.409189,54.157658,1018.366667,0,86.251351,2.521159
1,9110,4,244.984615,274.000000,309.157143,81.356696,22.581551,26.084600,32.683429,Montréal,2023,65.354444,63.901235,1011.552469,0,87.067778,4.344199
2,9141,4,307.289474,186.954545,302.485714,114.077605,33.502279,49.769409,30.840477,Spa-Francorchamps,2023,64.172000,61.926667,966.627333,1,82.833200,3.567269
3,9149,4,269.078125,259.527778,279.109375,120.639662,64.688944,30.031875,25.963431,Zandvoort,2023,62.225359,70.775120,1007.824402,1,76.894067,6.311765
4,9189,4,167.666667,190.000000,237.500000,119.327000,32.584000,37.438000,48.730000,Las Vegas,2023,64.490000,47.361111,939.781481,0,64.390000,5.147171
5,9472,4,233.605263,256.491228,296.325581,97.339857,31.555000,41.861333,23.954544,Sakhir,2024,64.809299,48.821656,1017.185987,0,74.575159,1.758254
6,9531,4,212.203390,265.228571,283.671429,90.508464,25.849652,28.711857,36.030443,Montréal,2024,62.810545,75.703030,996.332727,1,73.665091,2.687112
7,9558,4,295.934783,255.538462,301.634615,95.240373,31.022784,38.232865,25.980173,Silverstone,2024,60.387347,67.333333,992.126531,1,81.806122,3.016146
8,9644,4,178.756098,207.460000,314.880000,99.235959,29.067122,33.182880,37.010720,Las Vegas,2024,65.450435,51.033816,961.326087,0,68.084348,6.770437
9,9673,4,259.808511,253.767857,291.727273,108.396418,28.763054,32.629250,47.009357,Shanghai,2024,65.550909,66.060606,1011.452121,0,85.626909,3.758160

--- Windy Races ---

In [14]:
windy_race = pd.read_csv('../data/windy_race.csv') # reads in csv of all the windy races
lando_windy = type_to_df(windy_race)
lando_windy

,session_key,driver_number,i1_speed,i2_speed,st_speed,lap_duration,duration_sector_1,duration_sector_2,duration_sector_3,location,year,air_temperature,humidity,pressure,rainfall,track_temperature,wind_speed
0,9078,4,210.306122,184.912281,305.543860,93.539375,31.907214,35.505877,26.184125,Miami,2023,80.811355,59.425806,1018.378710,0,98.040258,8.881612
1,9126,4,276.950000,249.115385,283.615385,98.513431,32.141706,39.422135,26.900904,Silverstone,2023,70.652318,56.185430,1001.225828,0,87.693907,6.764332
2,9149,4,269.078125,259.527778,279.109375,120.639662,64.688944,30.031875,25.963431,Zandvoort,2023,62.225359,70.775120,1007.824402,1,76.894067,6.311765
3,9189,4,167.666667,190.000000,237.500000,119.327000,32.584000,37.438000,48.730000,Las Vegas,2023,64.490000,47.361111,939.781481,0,64.390000,5.147171
4,9213,4,211.600000,182.857143,295.250000,102.370545,28.062491,40.855750,33.441929,Austin,2023,85.928214,41.910714,993.730952,0,105.131429,7.414057
5,9496,4,278.157895,296.584906,293.320755,129.971442,67.424385,43.851736,19.364226,Suzuka,2024,71.044088,43.430939,1012.372376,0,99.501989,5.012857
6,9507,4,205.755556,181.631579,306.298246,95.552804,32.446018,36.359158,26.730667,Miami,2024,83.339452,59.047945,1016.451370,0,112.272603,6.867284
7,9582,4,286.823529,265.283582,296.721311,75.642409,25.744818,27.356209,22.545955,Zandvoort,2024,66.176575,61.047945,1019.978767,0,87.347534,10.135449
8,9625,4,281.469697,276.338028,320.403509,85.017157,30.588243,32.754620,21.991324,Mexico City,2024,67.799623,51.050314,785.252830,0,96.084528,4.811660
9,9644,4,178.756098,207.460000,314.880000,99.235959,29.067122,33.182880,37.010720,Las Vegas,2024,65.450435,51.033816,961.326087,0,68.084348,6.770437

--- Average Weather Races ---

In [16]:
avg_race = pd.read_csv('../data/avg_race.csv') # reads in csv of all the average weather races
lando_avg_weather = type_to_df(avg_race)
lando_avg_weather

,session_key,driver_number,i1_speed,i2_speed,st_speed,lap_duration,duration_sector_1,duration_sector_2,duration_sector_3,location,year,air_temperature,humidity,pressure,rainfall,track_temperature,wind_speed
0,7779,4,281.542857,299.520000,303.800000,99.081959,36.846265,31.017400,31.226800,Jeddah,2023,78.965405,57.790541,1010.929730,0,89.226622,3.964629
1,9070,4,188.104167,200.235294,314.901961,110.547980,39.435260,44.769392,26.321412,Baku,2023,76.749125,49.225000,1008.646250,0,106.178000,2.422951
2,9102,4,261.500000,265.384615,303.693878,81.514094,25.029234,32.225277,24.348431,Barcelona,2023,72.813247,63.077922,1001.090909,0,92.910130,4.182028
3,9126,4,276.950000,249.115385,283.615385,98.513431,32.141706,39.422135,26.900904,Silverstone,2023,70.652318,56.185430,1001.225828,0,87.693907,6.764332
4,9181,4,272.895522,277.535211,327.470588,104.123943,48.384614,33.179296,22.608183,Mexico City,2023,77.985263,23.552632,779.520526,0,114.151053,3.333130
5,9480,4,277.162162,290.120000,293.660000,97.735816,35.675918,30.803340,31.221040,Jeddah,2024,77.950548,62.335616,1012.682877,0,88.867671,2.914229
6,9496,4,278.157895,296.584906,293.320755,129.971442,67.424385,43.851736,19.364226,Suzuka,2024,71.044088,43.430939,1012.372376,0,99.501989,5.012857
7,9515,4,216.865385,255.682540,291.190476,81.326016,25.822565,28.297127,27.202016,Imola,2024,77.205175,48.426573,1006.634266,0,107.642797,4.789996
8,9523,4,192.633803,185.679487,278.910256,79.690416,20.650818,37.124205,22.051519,Monaco,2024,70.873700,63.990000,1018.743500,0,115.372400,2.191142
9,9574,4,327.473684,203.209302,315.225806,109.151667,31.559256,48.406884,29.240860,Spa-Francorchamps,2024,70.389333,49.622222,978.096296,0,108.064000,3.764788
10,9598,4,190.914894,206.196078,314.627451,109.807780,39.580660,44.239941,26.078353,Baku,2024,80.070658,38.019737,1017.640132,0,111.828816,3.470293

In [17]:
lando_avg_weather.to_csv('../data/clean/lando_avg_weather.csv')
lando_windy.to_csv('../data/clean/lando_windy.csv')
lando_cold.to_csv('../data/clean/lando_cold.csv')
lando_hot.to_csv('../data/clean/lando_hot.csv')
lando_rain.to_csv('../data/clean/lando_rain.csv')