In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
def type_to_df(df):
    df = df[['location','session_key','year','air_temperature','humidity','pressure','rainfall','track_temperature','wind_speed']]
    df_list = df.session_key.to_list()
    driver_df = leclerc_avg[leclerc_avg.session_key.isin(df_list)]
    driver_df = driver_df.merge(df, on = 'session_key', how = 'inner')
    return driver_df

In [3]:
leclerc_laps = pd.read_csv('../data/leclerc_laps.csv') # reads in Leclerc's lap stats
leclerc_laps = leclerc_laps[['session_key','driver_number','i1_speed','i2_speed','st_speed','lap_duration','duration_sector_1','duration_sector_2','duration_sector_3']]
# reduces df to only necessary columns
leclerc_avg = leclerc_laps.groupby(['session_key','driver_number']).agg({'i1_speed':'mean','i2_speed':'mean','st_speed':'mean','lap_duration':'mean','duration_sector_1':'mean','duration_sector_2':'mean','duration_sector_3':'mean'})
# avgerages out all the lap data by each race
leclerc_avg = leclerc_avg.reset_index()
leclerc_avg

,session_key,driver_number,i1_speed,i2_speed,st_speed,lap_duration,duration_sector_1,duration_sector_2,duration_sector_3
0,7779,16,276.366667,293.660000,301.820000,98.260204,36.172878,30.845160,31.239080
1,7787,16,NaN,NaN,243.000000,NaN,NaN,NaN,NaN
2,7953,16,227.964286,243.425000,297.647059,99.628632,32.424487,42.945825,24.206821
3,9070,16,203.695652,209.392157,311.294118,109.470880,38.889820,44.192627,26.362961
4,9078,16,213.733333,185.614035,316.491228,93.050482,31.995232,35.161667,25.916491
5,9094,16,181.861111,172.346154,273.038462,84.477429,22.011143,39.984833,22.460744
6,9102,16,271.317460,279.287879,314.203704,80.870292,24.329754,32.166621,24.403909
7,9110,16,243.821429,269.757143,303.142857,80.701449,22.330435,25.903357,32.468143
8,9118,16,293.222222,227.295775,294.112676,72.277514,18.702700,31.719887,21.925394
9,9126,16,283.833333,246.403846,294.326923,98.771118,32.350490,39.300846,27.088615
10,9133,16,278.114754,237.542857,292.127660,84.965551,30.932348,30.150371,23.911514
11,9141,16,305.358974,190.750000,302.800000,113.212209,33.126349,49.432295,30.648591
12,9149,16,275.562500,260.121951,278.631579,86.963600,30.277525,30.624171,26.340805
13,9157,16,315.162791,322.862745,326.760870,86.875300,28.529820,29.873588,28.475529
14,9165,16,282.547170,254.790323,272.770833,103.509033,30.497656,44.065645,28.935935
15,9173,16,268.577778,288.452830,287.169811,103.376077,38.073654,45.472434,20.272491
16,9181,16,281.071429,275.478873,318.206897,104.095829,48.202357,33.319662,22.562056
17,9189,16,172.613636,202.680000,289.520000,107.000245,30.416980,35.503080,41.007060
18,9197,16,285.102041,299.396552,305.155172,90.306982,18.855842,38.410172,33.056603
19,9213,16,209.760000,181.482143,300.785714,102.591673,27.818164,41.034000,33.740893
20,9221,16,226.823529,276.210526,291.301887,92.552518,34.838161,30.435105,27.619895
21,9472,16,234.883721,258.052632,299.320000,97.252500,31.594268,41.813930,23.835982
22,9480,16,279.400000,291.000000,302.800000,97.249612,35.636204,30.664180,30.907000
23,9488,16,273.714286,303.137931,289.509804,83.134895,28.882860,18.227741,36.033534
24,9496,16,274.955556,293.905660,291.641509,129.529712,66.969038,43.983566,19.576509
25,9507,16,205.040000,181.087719,308.192982,95.787482,32.854107,36.211579,26.695088
26,9515,16,214.500000,253.222222,287.587302,81.428839,25.992145,28.262349,27.177968
27,9523,16,198.866667,181.833333,275.128205,79.730182,20.630169,37.041859,22.179545
28,9531,16,199.350000,256.097561,288.585366,95.612718,27.740300,30.022415,37.903125
29,9539,16,270.366667,278.227273,311.148148,80.577123,24.041769,32.302030,24.242545
30,9550,16,301.089552,224.521127,301.070423,72.110986,18.690686,31.872620,21.635676
31,9558,16,291.534884,250.411765,301.568627,97.757380,32.050140,39.218412,26.470412
32,9566,16,281.232143,239.857143,291.688889,84.209522,30.520710,29.839514,23.881700
33,9574,16,315.050000,203.767442,311.500000,109.205143,31.936953,47.895000,29.373302
34,9582,16,286.800000,267.606061,306.545455,75.945508,25.953708,27.468909,22.545727
35,9590,16,315.666667,320.641509,324.477273,84.472077,27.862500,28.630547,28.012566
36,9598,16,197.893617,210.686275,316.431373,109.536220,39.529080,44.075353,25.945471
37,9606,16,300.403509,267.790323,288.272727,98.490344,29.131049,41.766548,27.643935
38,9617,16,215.416667,178.892857,298.642857,101.993673,27.479564,40.474679,34.000018
39,9625,16,286.030303,276.183099,316.690909,85.419443,30.790186,32.894127,22.065901
40,9636,16,283.019608,214.550725,249.044776,111.024103,43.750765,46.809116,20.440522
41,9644,16,177.853659,208.720000,313.620000,98.701429,28.836245,33.076140,36.789740
42,9655,16,226.846154,270.934783,277.475000,97.774348,36.149652,31.747000,30.297596
43,9662,16,287.780000,299.105263,311.000000,89.917607,18.370589,38.521456,33.057649
44,9673,16,253.302326,255.982143,296.642857,108.539800,28.909054,32.698232,47.077821

In [4]:
rain_race = pd.read_csv('../data/rain_race.csv') # reads in csv of all the rain races
leclerc_rain = type_to_df(rain_race)
leclerc_rain

,session_key,driver_number,i1_speed,i2_speed,st_speed,lap_duration,duration_sector_1,duration_sector_2,duration_sector_3,location,year,air_temperature,humidity,pressure,rainfall,track_temperature,wind_speed
0,9094,16,181.861111,172.346154,273.038462,84.477429,22.011143,39.984833,22.460744,Monaco,2023,77.118636,45.863636,1013.359659,1,102.660227,2.249710
1,9118,16,293.222222,227.295775,294.112676,72.277514,18.702700,31.719887,21.925394,Spielberg,2023,72.316471,52.045752,934.015686,1,89.697647,2.454852
2,9141,16,305.358974,190.750000,302.800000,113.212209,33.126349,49.432295,30.648591,Spa-Francorchamps,2023,64.172000,61.926667,966.627333,1,82.833200,3.567269
3,9149,16,275.562500,260.121951,278.631579,86.963600,30.277525,30.624171,26.340805,Zandvoort,2023,62.225359,70.775120,1007.824402,1,76.894067,6.311765
4,9531,16,199.350000,256.097561,288.585366,95.612718,27.740300,30.022415,37.903125,Montréal,2024,62.810545,75.703030,996.332727,1,73.665091,2.687112
5,9539,16,270.366667,278.227273,311.148148,80.577123,24.041769,32.302030,24.242545,Barcelona,2024,75.423567,63.433121,1001.353503,1,105.931847,4.740445
6,9550,16,301.089552,224.521127,301.070423,72.110986,18.690686,31.872620,21.635676,Spielberg,2024,84.966573,35.006993,932.862937,1,115.557762,3.730941
7,9558,16,291.534884,250.411765,301.568627,97.757380,32.050140,39.218412,26.470412,Silverstone,2024,60.387347,67.333333,992.126531,1,81.806122,3.016146
8,9636,16,283.019608,214.550725,249.044776,111.024103,43.750765,46.809116,20.440522,São Paulo,2024,70.992836,85.258706,926.456716,1,78.385373,1.646031

In [5]:
hot_race = pd.read_csv('../data/hot_race.csv') # reads in csv of all the hot races
leclerc_hot = type_to_df(hot_race)
leclerc_hot

,session_key,driver_number,i1_speed,i2_speed,st_speed,lap_duration,duration_sector_1,duration_sector_2,duration_sector_3,location,year,air_temperature,humidity,pressure,rainfall,track_temperature,wind_speed
0,9133,16,278.114754,237.542857,292.127660,84.965551,30.932348,30.150371,23.911514,Budapest,2023,83.855366,32.804878,988.401829,0,119.442683,3.223190
1,9157,16,315.162791,322.862745,326.760870,86.875300,28.529820,29.873588,28.475529,Monza,2023,84.794231,42.320513,1000.561538,0,109.270769,2.549606
2,9165,16,282.547170,254.790323,272.770833,103.509033,30.497656,44.065645,28.935935,Marina Bay,2023,85.719773,72.028409,1008.978409,0,97.559886,3.167389
3,9213,16,209.760000,181.482143,300.785714,102.591673,27.818164,41.034000,33.740893,Austin,2023,85.928214,41.910714,993.730952,0,105.131429,7.414057
4,9221,16,226.823529,276.210526,291.301887,92.552518,34.838161,30.435105,27.619895,Lusail,2023,88.628228,73.177215,1009.776582,0,98.465570,1.986399
5,9507,16,205.040000,181.087719,308.192982,95.787482,32.854107,36.211579,26.695088,Miami,2024,83.339452,59.047945,1016.451370,0,112.272603,6.867284
6,9550,16,301.089552,224.521127,301.070423,72.110986,18.690686,31.872620,21.635676,Spielberg,2024,84.966573,35.006993,932.862937,1,115.557762,3.730941
7,9566,16,281.232143,239.857143,291.688889,84.209522,30.520710,29.839514,23.881700,Budapest,2024,83.882968,46.922581,981.676774,0,112.849032,2.795528
8,9590,16,315.666667,320.641509,324.477273,84.472077,27.862500,28.630547,28.012566,Monza,2024,91.582707,32.285714,993.228571,0,120.760301,3.397549
9,9606,16,300.403509,267.790323,288.272727,98.490344,29.131049,41.766548,27.643935,Marina Bay,2024,87.415250,74.650000,1008.024375,0,97.602125,2.136335

In [6]:
cold_race = pd.read_csv('../data/cold_race.csv') # reads in csv of all the cold races
leclerc_cold = type_to_df(cold_race)
leclerc_cold

,session_key,driver_number,i1_speed,i2_speed,st_speed,lap_duration,duration_sector_1,duration_sector_2,duration_sector_3,location,year,air_temperature,humidity,pressure,rainfall,track_temperature,wind_speed
0,7787,16,NaN,NaN,243.000000,NaN,NaN,NaN,NaN,Melbourne,2023,63.409189,54.157658,1018.366667,0,86.251351,2.521159
1,9110,16,243.821429,269.757143,303.142857,80.701449,22.330435,25.903357,32.468143,Montréal,2023,65.354444,63.901235,1011.552469,0,87.067778,4.344199
2,9141,16,305.358974,190.750000,302.800000,113.212209,33.126349,49.432295,30.648591,Spa-Francorchamps,2023,64.172000,61.926667,966.627333,1,82.833200,3.567269
3,9149,16,275.562500,260.121951,278.631579,86.963600,30.277525,30.624171,26.340805,Zandvoort,2023,62.225359,70.775120,1007.824402,1,76.894067,6.311765
4,9189,16,172.613636,202.680000,289.520000,107.000245,30.416980,35.503080,41.007060,Las Vegas,2023,64.490000,47.361111,939.781481,0,64.390000,5.147171
5,9472,16,234.883721,258.052632,299.320000,97.252500,31.594268,41.813930,23.835982,Sakhir,2024,64.809299,48.821656,1017.185987,0,74.575159,1.758254
6,9531,16,199.350000,256.097561,288.585366,95.612718,27.740300,30.022415,37.903125,Montréal,2024,62.810545,75.703030,996.332727,1,73.665091,2.687112
7,9558,16,291.534884,250.411765,301.568627,97.757380,32.050140,39.218412,26.470412,Silverstone,2024,60.387347,67.333333,992.126531,1,81.806122,3.016146
8,9644,16,177.853659,208.720000,313.620000,98.701429,28.836245,33.076140,36.789740,Las Vegas,2024,65.450435,51.033816,961.326087,0,68.084348,6.770437
9,9673,16,253.302326,255.982143,296.642857,108.539800,28.909054,32.698232,47.077821,Shanghai,2024,65.550909,66.060606,1011.452121,0,85.626909,3.758160

In [7]:
windy_race = pd.read_csv('../data/windy_race.csv') # reads in csv of all the windy races
leclerc_windy = type_to_df(windy_race)
leclerc_windy

,session_key,driver_number,i1_speed,i2_speed,st_speed,lap_duration,duration_sector_1,duration_sector_2,duration_sector_3,location,year,air_temperature,humidity,pressure,rainfall,track_temperature,wind_speed
0,9078,16,213.733333,185.614035,316.491228,93.050482,31.995232,35.161667,25.916491,Miami,2023,80.811355,59.425806,1018.378710,0,98.040258,8.881612
1,9126,16,283.833333,246.403846,294.326923,98.771118,32.350490,39.300846,27.088615,Silverstone,2023,70.652318,56.185430,1001.225828,0,87.693907,6.764332
2,9149,16,275.562500,260.121951,278.631579,86.963600,30.277525,30.624171,26.340805,Zandvoort,2023,62.225359,70.775120,1007.824402,1,76.894067,6.311765
3,9189,16,172.613636,202.680000,289.520000,107.000245,30.416980,35.503080,41.007060,Las Vegas,2023,64.490000,47.361111,939.781481,0,64.390000,5.147171
4,9213,16,209.760000,181.482143,300.785714,102.591673,27.818164,41.034000,33.740893,Austin,2023,85.928214,41.910714,993.730952,0,105.131429,7.414057
5,9496,16,274.955556,293.905660,291.641509,129.529712,66.969038,43.983566,19.576509,Suzuka,2024,71.044088,43.430939,1012.372376,0,99.501989,5.012857
6,9507,16,205.040000,181.087719,308.192982,95.787482,32.854107,36.211579,26.695088,Miami,2024,83.339452,59.047945,1016.451370,0,112.272603,6.867284
7,9582,16,286.800000,267.606061,306.545455,75.945508,25.953708,27.468909,22.545727,Zandvoort,2024,66.176575,61.047945,1019.978767,0,87.347534,10.135449
8,9625,16,286.030303,276.183099,316.690909,85.419443,30.790186,32.894127,22.065901,Mexico City,2024,67.799623,51.050314,785.252830,0,96.084528,4.811660
9,9644,16,177.853659,208.720000,313.620000,98.701429,28.836245,33.076140,36.789740,Las Vegas,2024,65.450435,51.033816,961.326087,0,68.084348,6.770437

In [8]:
avg_race = pd.read_csv('../data/avg_race.csv') # reads in csv of all the average weather races
leclerc_avg_weather = type_to_df(avg_race)
leclerc_avg_weather

,session_key,driver_number,i1_speed,i2_speed,st_speed,lap_duration,duration_sector_1,duration_sector_2,duration_sector_3,location,year,air_temperature,humidity,pressure,rainfall,track_temperature,wind_speed
0,7779,16,276.366667,293.660000,301.820000,98.260204,36.172878,30.845160,31.239080,Jeddah,2023,78.965405,57.790541,1010.929730,0,89.226622,3.964629
1,9070,16,203.695652,209.392157,311.294118,109.470880,38.889820,44.192627,26.362961,Baku,2023,76.749125,49.225000,1008.646250,0,106.178000,2.422951
2,9102,16,271.317460,279.287879,314.203704,80.870292,24.329754,32.166621,24.403909,Barcelona,2023,72.813247,63.077922,1001.090909,0,92.910130,4.182028
3,9126,16,283.833333,246.403846,294.326923,98.771118,32.350490,39.300846,27.088615,Silverstone,2023,70.652318,56.185430,1001.225828,0,87.693907,6.764332
4,9181,16,281.071429,275.478873,318.206897,104.095829,48.202357,33.319662,22.562056,Mexico City,2023,77.985263,23.552632,779.520526,0,114.151053,3.333130
5,9480,16,279.400000,291.000000,302.800000,97.249612,35.636204,30.664180,30.907000,Jeddah,2024,77.950548,62.335616,1012.682877,0,88.867671,2.914229
6,9496,16,274.955556,293.905660,291.641509,129.529712,66.969038,43.983566,19.576509,Suzuka,2024,71.044088,43.430939,1012.372376,0,99.501989,5.012857
7,9515,16,214.500000,253.222222,287.587302,81.428839,25.992145,28.262349,27.177968,Imola,2024,77.205175,48.426573,1006.634266,0,107.642797,4.789996
8,9523,16,198.866667,181.833333,275.128205,79.730182,20.630169,37.041859,22.179545,Monaco,2024,70.873700,63.990000,1018.743500,0,115.372400,2.191142
9,9574,16,315.050000,203.767442,311.500000,109.205143,31.936953,47.895000,29.373302,Spa-Francorchamps,2024,70.389333,49.622222,978.096296,0,108.064000,3.764788
10,9598,16,197.893617,210.686275,316.431373,109.536220,39.529080,44.075353,25.945471,Baku,2024,80.070658,38.019737,1017.640132,0,111.828816,3.470293

In [9]:
leclerc_avg_weather.to_csv('../data/clean/leclerc_avg_weather.csv')
leclerc_windy.to_csv('../data/clean/leclerc_windy.csv')
leclerc_cold.to_csv('../data/clean/leclerc_cold.csv')
leclerc_hot.to_csv('../data/clean/leclerc_hot.csv')
leclerc_rain.to_csv('../data/clean/leclerc_rain.csv')